// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk2raRX_0ON2pmHZbBfSI-yduQc2r4Gfk',
    appId: '1:532632325358:web:2f18045e2bc7223b16b7ff',
    messagingSenderId: '532632325358',
    projectId: 'recognizemeia-c4f9a',
    authDomain: 'recognizemeia-c4f9a.firebaseapp.com',
    storageBucket: 'recognizemeia-c4f9a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKeGLCWvFXV0Y-DChf2Tz3pYflSexS_Ok',
    appId: '1:532632325358:android:49339035ad27c0f016b7ff',
    messagingSenderId: '532632325358',
    projectId: 'recognizemeia-c4f9a',
    storageBucket: 'recognizemeia-c4f9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWJto02PHNlfSCraEo2Gfd5iO-8qsHs3Q',
    appId: '1:532632325358:ios:189cd511f782e5c616b7ff',
    messagingSenderId: '532632325358',
    projectId: 'recognizemeia-c4f9a',
    storageBucket: 'recognizemeia-c4f9a.appspot.com',
    iosBundleId: 'com.example.recognizemeIa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWJto02PHNlfSCraEo2Gfd5iO-8qsHs3Q',
    appId: '1:532632325358:ios:1315872c9f28816516b7ff',
    messagingSenderId: '532632325358',
    projectId: 'recognizemeia-c4f9a',
    storageBucket: 'recognizemeia-c4f9a.appspot.com',
    iosBundleId: 'com.example.recognizemeIa.RunnerTests',
  );
}
